#!/bin/bash

set -e

if [ "x$1" == "x" ]; then
  echo "usage: build tagname [ tagname [ ... ] ]"
  exit 2
fi

export ARCH=$(uname -m)

while [ "x$1" != "x" ]; do

  tag=$(echo $1 | sed 's/^.*\///')

  if [ -f "versions/$tag/Dockerfile" ]; then
    docker build -f versions/$tag/Dockerfile -t plicease/ciperl:"$tag" .
    ./retry docker push plicease/ciperl:"$tag"
  elif [ -f "base/$ARCH/$tag/Dockerfile" ]; then
    docker build -f base/$ARCH/$tag/Dockerfile -t plicease/ciperl-base:"$tag" .
    ./retry docker push plicease/ciperl-base:"$tag"
  else
    echo "no such tag: $tag"
    exit 2
  fi

  shift

done
