#!/bin/bash

set -ex

docker build -f base/Dockerfile -t plicease/ciperl-base .

for VERSION in 5.28.1 5.26.3 5.24.4 5.22.4 5.20.3 5.18.4 5.16.3 5.14.4 ; do
  mkdir -p versions/$VERSION
  sed "s/#PERL_VERSION#/$VERSION/g" < rc/Dockerfile.template > versions/$VERSION/Dockerfile
done

for VERSION in 5.29.5 ; do
  mkdir -p versions/$VERSION
  sed "s/#PERL_VERSION#/$VERSION/g" < rc/Dockerfile-dev.template > versions/$VERSION/Dockerfile
done

for VERSION in 5.12.5 5.10.1 5.10.0 5.8.9 5.8.8 5.8.1; do
  mkdir -p versions/$VERSION
  sed "s/#PERL_VERSION#/$VERSION/g" < rc/Dockerfile-old.template > versions/$VERSION/Dockerfile
done

for TAG in $(ls versions) ; do
  docker build -f versions/$TAG/Dockerfile -t plicease/ciperl:"$TAG" .
done
