#!/bin/bash

PATH="/opt/dzil/bin${PATH:+:${PATH}}"; export PATH;
PERL5LIB="/opt/dzil/lib/perl5"; export PERL5LIB;
PERL_LOCAL_LIB_ROOT="/opt/dzil"; export PERL_LOCAL_LIB_ROOT;
PERL_MB_OPT="--install_base \"/opt/dzil\""; export PERL_MB_OPT;
PERL_MM_OPT="INSTALL_BASE=/opt/dzil"; export PERL_MM_OPT;

exec cpanm "$@"
