#!/bin/bash

PATH="/home/cip/dzil/bin:/opt/dzil/bin:/opt/perl/5.30.3/bin${PATH:+:${PATH}}"; export PATH;
PERL5LIB="/home/cip/dzil/lib/perl5:/opt/dzil/lib/perl5"; export PERL5LIB;
PERL_LOCAL_LIB_ROOT="/home/cip/dzil"; export PERL_LOCAL_LIB_ROOT;
PERL_MB_OPT="--install_base \"/home/cip/dzil\""; export PERL_MB_OPT;
PERL_MM_OPT="INSTALL_BASE=/home/cip/dzil"; export PERL_MM_OPT;

exec cpanm "$@"
