#!/bin/bash

PATH="/opt/refileutils/bin${PATH:+:${PATH}}"; export PATH;
PERL5LIB="/opt/refileutils/lib/perl5"; export PERL5LIB;
PERL_LOCAL_LIB_ROOT="/opt/refileutils"; export PERL_LOCAL_LIB_ROOT;
PERL_MB_OPT="--install_base \"/opt/refileutils\""; export PERL_MB_OPT;
PERL_MM_OPT="INSTALL_BASE=/opt/refileutils"; export PERL_MM_OPT;

exec reln "$@"
